server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # 1. Gestion des fichiers statiques du Frontend (React/Vite)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Redirection interne vers le student-service
    location /api/students/ {
        proxy_pass http://student-service:5001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. Redirection interne vers le teacher-admin-service
    location /api/teachers/ {
        proxy_pass http://teacher-admin-service:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 4. Redirection interne vers le enrollment-service
    location /api/enrollments/ {
        proxy_pass http://enrollment-service:5003/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}