server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Seule responsabilité : servir l'application React / gestion du SPA Router
    location / {
        try_files $uri $uri/ /index.html;
    }
}