name: Test Creation Fichier Codespace

on:
  workflow_dispatch:

jobs:
  test-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Creer le fichier hehe.txt dans le Codespace
        env:
          GH_TOKEN: ${{ secrets.CODESPACE_PAT }}
          CODESPACE_NAME: ${{ vars.CODESPACE_NAME }}
        run: |
          # 1. Création du fichier avec du contenu
          gh codespace ssh -c "$CODESPACE_NAME" -- "echo 'Fichier cree par GitHub Actions' > /workspaces/hehe.txt"
          
          # 2. Vérification du contenu et de la présence du fichier
          echo "--- Verification du fichier ---"
          gh codespace ssh -c "$CODESPACE_NAME" -- "docker ps"
